image: node:20

clone:
  depth: full

pipelines:
  pull-requests:
    '**':
      - step:
          name: 'Install'
          script:
            - npm ci -f
          caches:
            - node
      - parallel:
        - step:
            name: 'Lint'
            script:
              - npx nx run-many --target=lint --all
            caches:
              - node
        - step:
            name: 'Build'
            script:
              - npx nx run-many --target=build --all
            caches:
              - node
        - step:
            name: 'Test'
            script:
              - npx nx run-many --target=test -projects=calendar-backend,calendar-frontend,calendar-domain --all
            caches:
              - node

  branches:
    master:
      - step:
          name: 'Install'
          script:
            - npm ci -f
          caches:
            - node
      - parallel:
          - step:
              name: 'Lint'
              script:
                - npx nx run-many --target=lint --all
              caches:
                - node
          - step:
              name: 'Build'
              script:
                - npx nx run-many --target=build --all
              caches:
                - node
          - step:
              name: 'Test'
              script:
                - npx nx run-many --target=test -projects=calendar-backend,calendar-frontend,calendar-domain --all
              caches:
                - node
